# Generated by Django 5.0.4 on 2024-04-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_like_user_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like_count',
        ),
    ]
